# Generated by Django 3.1.4 on 2020-12-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20201230_1409'),
        ('MyApp', '0005_auto_20201229_2255'),
    ]

    operations = [
    ]
