# Generated by Django 3.1.4 on 2021-01-01 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0006_merge_20201230_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linksthemes',
            options={'verbose_name': 'Тема для ссылки', 'verbose_name_plural': 'Темы для ссылок'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='links',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='MyApp.linksthemes'),
        ),
    ]
