# Generated by Django 3.1.4 on 2021-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20210103_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Russia', max_length=100),
            preserve_default=False,
        ),
    ]
